project:
  type: website
  output-dir: _site
  resources:
    - notes/pdf/
    - cv/*.pdf

website:
  title: "Patrick Oare"
  site-url: "https://www.patrickoare.phd"
  search: true
  navbar:
    left:
      - text: "About"
        href: about.md
      - text: "CV"
        href: cv/index.md
      - text: "Notes"
        href: notes/index.md
      - text: "Blog"
        href: blog/index.md

format:
  html:
    theme: theme.scss
    toc: false
    html-math-method:
      method: katex
      url: "https://cdn.jsdelivr.net/npm/katex@0.18.1/dist/"
